### ISSUE TITLE
Slack adapter compatibility...

### ISSUE THREAD

**Issue by MrJoy** [killpack/lita-down-for-everyone#4]
When getting a message from Slack, it wraps up the URL so the message your plugin actually sees looks like: `is <http://github.com|github.com> down?`.

**Comment by killpack** [comment]
I'll try and get to this when I have a chance, but feel free to submit a PR if you want.

**Comment by Rudikza** [comment]
@killpack We just started using Lita and have Slack integration so I decided to fix this bug, checkout https://github.com/killpack/lita-down-for-everyone/pull/5 and let me know if it's ok or if I need to change anything?

**Comment by killpack** [comment]
Yep, this is fixed as of 0.0.4.
